version: '3'
services:
  mars-viewer:
    build: 
      context: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - ignore:/app/node_modules/
volumes:
  ignore:
